import {
  IconAtom,
  IconBolt,
  IconBriefcase,
  IconBuildingFactory2,
  IconBuildingSkyscraper,
  IconCalculator,
  IconCamera,
  IconCertificate,
  IconClipboardList,
  IconDeviceDesktop,
  IconFileDescription,
  IconFlame,
  IconGavel,
  IconHeartbeat,
  IconHome,
  IconInfoCircle,
  IconLeaf,
  IconMail,
  IconMapPin,
  IconPhoto,
  IconSatellite,
  IconSchool,
  IconScissors,
  IconSpeakerphone,
  IconTool,
  IconUsers,
} from "@tabler/icons-react";
import type { DropdownSection, NavLink } from "./types";

export const COLOR_MAP = {
  blue: {
    badgeBg: "var(--badge-blue-bg)",
    badgeText: "var(--badge-blue-text)",
    infoBg: "var(--info-bg)",
    infoText: "var(--info-text)",
    infoBorder: "var(--info-border)",
  },
  red: {
    badgeBg: "var(--badge-red-bg)",
    badgeText: "var(--badge-red-text)",
    infoBg: "var(--error-bg)",
    infoText: "var(--error-text)",
    infoBorder: "var(--error-border)",
  },
  success: {
    badgeBg: "var(--success-bg)",
    badgeText: "var(--success-text)",
    infoBg: "var(--success-bg)",
    infoText: "var(--success-text)",
    infoBorder: "var(--success-border)",
  },
  warning: {
    badgeBg: "var(--warning-bg)",
    badgeText: "var(--warning-text)",
    infoBg: "var(--warning-bg)",
    infoText: "var(--warning-text)",
    infoBorder: "var(--warning-border)",
  },
} as const;

export const ITEM_BADGE_MAP = {
  popular: {
    bg: "var(--badge-red-bg)",
    color: "var(--badge-red-text)",
    label: "Popular",
  },
  new: { bg: "var(--success-bg)", color: "var(--success-text)", label: "New" },
  demand: {
    bg: "var(--warning-bg)",
    color: "var(--warning-text)",
    label: "In Demand",
  },
  prestige: {
    bg: "var(--badge-blue-bg)",
    color: "var(--badge-blue-text)",
    label: "Prestigious",
  },
} as const;

export const LANGUAGES = [
  { code: "en", label: "EN", full: "English" },
  { code: "fr", label: "FR", full: "Français" },
];

export const PROGRAMS_DROPDOWN: DropdownSection[] = [
  {
    heading: "Commerce & Finance",
    sectionBadge: "ND / BTS / Degree",
    color: "blue",
    viewAllHref: "/academics/commerce",
    viewAllLabel: "All Commerce Programs",
    items: [
      {
        label: "Accounting & Finance",
        href: "/academics/commerce/accounting",
        icon: <IconCalculator size={14} stroke={1.8} />,
        description: "Financial accounting, bookkeeping & auditing",
        badge: "demand",
      },
      {
        label: "Banking & Finance",
        href: "/academics/commerce/banking",
        icon: <IconBriefcase size={14} stroke={1.8} />,
        description: "Banking operations, credit & financial services",
      },
      {
        label: "Marketing & Sales",
        href: "/academics/commerce/marketing",
        icon: <IconSpeakerphone size={14} stroke={1.8} />,
        description: "Marketing, commerce & sales strategy",
        badge: "popular",
      },
      {
        label: "International Trade",
        href: "/academics/commerce/international",
        icon: <IconBuildingSkyscraper size={14} stroke={1.8} />,
        description: "International commerce & trade operations",
      },
      {
        label: "Project Management",
        href: "/academics/commerce/projects",
        icon: <IconClipboardList size={14} stroke={1.8} />,
        description: "Project planning, logistics & transport management",
      },
      {
        label: "Microfinance",
        href: "/academics/commerce/microfinance",
        icon: <IconCalculator size={14} stroke={1.8} />,
        description: "Microfinance, local taxation & NGO management",
        badge: "new",
      },
    ],
  },
  {
    heading: "Engineering & IT",
    sectionBadge: "ND / BTS / HND / MASTER",
    color: "blue",
    viewAllHref: "/academics/engineering",
    viewAllLabel: "All Engineering Programs",
    items: [
      {
        label: "Software Engineering",
        href: "/academics/engineering/software",
        icon: <IconDeviceDesktop size={14} stroke={1.8} />,
        description: "Software development, systems & applications",
        badge: "popular",
      },
      {
        label: "Computer Hardware",
        href: "/academics/engineering/hardware",
        icon: <IconTool size={14} stroke={1.8} />,
        description: "Hardware engineering & computer maintenance",
      },
      {
        label: "Telecommunications",
        href: "/academics/engineering/telecom",
        icon: <IconBolt size={14} stroke={1.8} />,
        description: "Telecom systems, networks & security",
        badge: "demand",
      },
      {
        label: "Civil & Construction Tech",
        href: "/academics/engineering/civil",
        icon: <IconBuildingFactory2 size={14} stroke={1.8} />,
        description: "Civil engineering, topography & urban planning",
      },
      {
        label: "Electrical Systems",
        href: "/academics/engineering/electrical",
        icon: <IconBolt size={14} stroke={1.8} />,
        description: "Electrical power systems & industrial maintenance",
      },
      {
        label: "Graphics & IT Design",
        href: "/academics/engineering/graphics",
        icon: <IconDeviceDesktop size={14} stroke={1.8} />,
        description: "IT graphics, web design & multimedia",
        badge: "new",
      },
    ],
  },
  {
    heading: "Health Sciences",
    sectionBadge: "ND / BTS / DEGREE",
    color: "red",
    viewAllHref: "/academics/health",
    viewAllLabel: "All Health Programs",
    items: [
      {
        label: "Nursing Sciences",
        href: "/academics/health/nursing",
        icon: <IconHeartbeat size={14} stroke={1.8} />,
        description: "Nursing care, patient management & clinical practice",
        badge: "popular",
      },
      {
        label: "Laboratory Technology",
        href: "/academics/health/laboratory",
        icon: <IconAtom size={14} stroke={1.8} />,
        description: "Medical laboratory techniques & bioanalysis",
      },
      {
        label: "Midwifery",
        href: "/academics/health/midwifery",
        icon: <IconHeartbeat size={14} stroke={1.8} />,
        description: "Maternal care, obstetrics & gynecological nursing",
      },
      {
        label: "Pharmacy Technology",
        href: "/academics/health/pharmacy",
        icon: <IconAtom size={14} stroke={1.8} />,
        description: "Pharmaceutical management & dispensing",
        badge: "demand",
      },
      {
        label: "Physiotherapy",
        href: "/academics/health/physio",
        icon: <IconHeartbeat size={14} stroke={1.8} />,
        description: "Physical rehabilitation & therapeutic care",
      },
      {
        label: "Nutrition & Dietetics",
        href: "/academics/health/nutrition",
        icon: <IconLeaf size={14} stroke={1.8} />,
        description: "Clinical nutrition, dietetics & food science",
        badge: "new",
      },
      {
        label: "Dental Therapy",
        href: "/academics/health/dental",
        icon: <IconHeartbeat size={14} stroke={1.8} />,
        description: "Oral health care & dental technology",
      },
      {
        label: "Clinical Optometry",
        href: "/academics/health/optometry",
        icon: <IconCamera size={14} stroke={1.8} />,
        description: "Eye care, vision science & clinical optometry",
      },
    ],
  },
  {
    heading: "Agriculture & Livestock",
    sectionBadge: "ND / BTS / DEGREE",
    color: "red",
    viewAllHref: "/academics/agriculture",
    viewAllLabel: "All Agriculture Programs",
    items: [
      {
        label: "Food Technology",
        href: "/academics/agriculture/food",
        icon: <IconLeaf size={14} stroke={1.8} />,
        description: "Food processing, preservation & quality control",
        badge: "demand",
      },
      {
        label: "Animal Production",
        href: "/academics/agriculture/animal",
        icon: <IconLeaf size={14} stroke={1.8} />,
        description: "Livestock management & veterinary support",
      },
      {
        label: "Agricultural Engineering",
        href: "/academics/agriculture/engineering",
        icon: <IconBuildingFactory2 size={14} stroke={1.8} />,
        description: "Agro-industrial systems & farm mechanization",
      },
      {
        label: "Agro-Pastoral Entrepreneurship",
        href: "/academics/agriculture/entrepreneurship",
        icon: <IconBriefcase size={14} stroke={1.8} />,
        description: "Agricultural business & rural entrepreneurship",
        badge: "new",
      },
      {
        label: "Plant Production (Agronomy)",
        href: "/academics/agriculture/agronomy",
        icon: <IconLeaf size={14} stroke={1.8} />,
        description: "Crop science, soil management & agronomy",
      },
      {
        label: "Farm Management",
        href: "/academics/agriculture/management",
        icon: <IconClipboardList size={14} stroke={1.8} />,
        description: "Agricultural management techniques & rural planning",
      },
    ],
  },
  {
    heading: "Education",
    sectionBadge: "CAPIEMP / CAPIET / MASTER",
    color: "blue",
    viewAllHref: "/academics/education",
    viewAllLabel: "All Education Programs",
    items: [
      {
        label: "Didactics & Teaching",
        href: "/academics/education/didactics",
        icon: <IconSchool size={14} stroke={1.8} />,
        description: "Teaching methods, curriculum development & pedagogy",
        badge: "popular",
      },
      {
        label: "Career Guidance & Counseling",
        href: "/academics/education/guidance",
        icon: <IconUsers size={14} stroke={1.8} />,
        description: "Orientation, professional studies & student counseling",
      },
      {
        label: "Educational Administration",
        href: "/academics/education/administration",
        icon: <IconClipboardList size={14} stroke={1.8} />,
        description: "School management & educational governance",
        badge: "demand",
      },
      {
        label: "Professional Education Studies",
        href: "/academics/education/professional",
        icon: <IconCertificate size={14} stroke={1.8} />,
        description: "Professional training & workplace education",
      },
      {
        label: "Educational Sciences",
        href: "/academics/education/sciences",
        icon: <IconAtom size={14} stroke={1.8} />,
        description: "Research, educational psychology & learning theory",
        badge: "new",
      },
    ],
  },
  {
    heading: "Tourism & Hospitality",
    sectionBadge: "ND / BTS / DEGREE",
    color: "red",
    viewAllHref: "/academics/hospitality",
    viewAllLabel: "All Hospitality Programs",
    items: [
      {
        label: "Bakery & Food Production",
        href: "/academics/hospitality/bakery",
        icon: <IconLeaf size={14} stroke={1.8} />,
        description: "Baking, culinary arts & food production management",
        badge: "popular",
      },
      {
        label: "Hotel & Restaurant Management",
        href: "/academics/hospitality/hotel",
        icon: <IconBuildingSkyscraper size={14} stroke={1.8} />,
        description: "Hospitality management & restaurant operations",
        badge: "demand",
      },
      {
        label: "Fashion & Textile",
        href: "/academics/hospitality/fashion",
        icon: <IconScissors size={14} stroke={1.8} />,
        description: "Fashion design, garment making & textile technology",
      },
      {
        label: "Travel & Tourism Agency",
        href: "/academics/hospitality/tourism",
        icon: <IconMapPin size={14} stroke={1.8} />,
        description: "Tourism operations, travel management & guiding",
        badge: "new",
      },
    ],
  },
  {
    heading: "Other Professional",
    sectionBadge: "ND / BTS / DEGREE",
    color: "red",
    viewAllHref: "/academics/other",
    viewAllLabel: "All Other Programs",
    items: [
      {
        label: "Mechanical Engineering",
        href: "/academics/other/mechanical",
        icon: <IconTool size={14} stroke={1.8} />,
        description: "Mechanical systems, maintenance & production",
      },
      {
        label: "Petroleum Engineering",
        href: "/academics/other/petroleum",
        icon: <IconFlame size={14} stroke={1.8} />,
        description: "Petroleum technology & mining engineering",
        badge: "demand",
      },
      {
        label: "Legal Careers",
        href: "/academics/other/legal",
        icon: <IconGavel size={14} stroke={1.8} />,
        description: "Law, legal practice & judicial administration",
        badge: "prestige",
      },
      {
        label: "Communication",
        href: "/academics/other/communication",
        icon: <IconSpeakerphone size={14} stroke={1.8} />,
        description: "Media, communication & public relations",
        badge: "new",
      },
      {
        label: "Electronic Engineering",
        href: "/academics/other/electronics",
        icon: <IconBolt size={14} stroke={1.8} />,
        description: "Electronic systems, circuits & instrumentation",
      },
    ],
  },
  {
    heading: "CQP / DQP Short Courses",
    sectionBadge: "CQP / DQP / AQP",
    color: "blue",
    viewAllHref: "/academics/cqp",
    viewAllLabel: "All Short Courses",
    items: [
      {
        label: "Secretarial & Office Work",
        href: "/academics/cqp/secretarial",
        icon: <IconFileDescription size={14} stroke={1.8} />,
        description: "Office management, typing & administrative support",
        badge: "popular",
      },
      {
        label: "Computerized Accounting",
        href: "/academics/cqp/accounting",
        icon: <IconCalculator size={14} stroke={1.8} />,
        description: "Digital bookkeeping & accounting software",
        badge: "demand",
      },
      {
        label: "Graphics & Web Design",
        href: "/academics/cqp/graphics",
        icon: <IconDeviceDesktop size={14} stroke={1.8} />,
        description: "Graphic design, web development & digital media",
      },
      {
        label: "Computer Maintenance",
        href: "/academics/cqp/maintenance",
        icon: <IconTool size={14} stroke={1.8} />,
        description: "PC hardware maintenance & repair techniques",
      },
      {
        label: "CCTV & Surveillance Installation",
        href: "/academics/cqp/cctv",
        icon: <IconCamera size={14} stroke={1.8} />,
        description: "Security camera installation & monitoring systems",
        badge: "new",
      },
      {
        label: "Satellite Dish Installation",
        href: "/academics/cqp/satellite",
        icon: <IconSatellite size={14} stroke={1.8} />,
        description: "Parabolic antenna installation & satellite systems",
      },
      {
        label: "Solar Energy Installation",
        href: "/academics/cqp/solar",
        icon: <IconBolt size={14} stroke={1.8} />,
        description: "Solar panel installation & renewable energy systems",
        badge: "demand",
      },
    ],
  },
];

export const NAV_LINKS: NavLink[] = [
  { label: "Home", href: "/", icon: <IconHome size={15} stroke={1.8} /> },
  {
    label: "About",
    href: "/about",
    icon: <IconInfoCircle size={15} stroke={1.8} />,
  },
  {
    label: "Programs",
    href: "/academics",
    icon: <IconBriefcase size={15} stroke={1.8} />,
    dropdown: PROGRAMS_DROPDOWN,
  },
  {
    label: "Admissions",
    href: "/admissions",
    icon: <IconClipboardList size={15} stroke={1.8} />,
  },
  {
    label: "Gallery",
    href: "/gallery",
    icon: <IconPhoto size={15} stroke={1.8} />,
  },
  {
    label: "Contact",
    href: "/contact",
    icon: <IconMail size={15} stroke={1.8} />,
  },
];
